blank_issues_enabled: false
contact_links:
  - name: â“ Ask a Question
    url: https://github.com/EveryVoiceTTS/EveryVoice/discussions
    about: Ask and answer EveryVoice TTS related questions.
  - name: ğŸ“– Read the documentation
    url: https://docs.everyvoice.ca/
    about: Please consult the documentation before opening any issues!